### ISSUE TITLE
fix npm 3 module resolution

### ISSUE THREAD

**Issue by yoshuawuyts** [hughsk/disc#59]
I propose we switch to use https://github.com/npm/read-package-tree so we can correctly parse npm 3's dependency tree

**Comment by yoshuawuyts** [comment]
derp, that won't work tho - digging in further.

**Comment by yoshuawuyts** [comment]
ok, can't find a bug in the code. Looks like we're doing everything by the textbook. E.g.
1. get a browserify bundle
2. parse it with https://github.com/substack/browser-unpack which gets the filepaths, deps and stuff
4. filter and shape as a tree that can d3 can parse

It seems browserify's full path algorithm needs tweaking if it's not going well; the relationship between deps and the like should _just work_ hmmm

**Comment by yoshuawuyts** [comment]
lol ok everything actually works as expected. Seems like this is no longer an issue :sparkles: yay

**Comment by hughsk** [comment]
Haha! Adding you to the repo for posterity :)

**Comment by yoshuawuyts** [comment]
:D
